config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :cars, only: [:index, :show] do
    resources :bookings, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :brand, presence: true
  validates :model, presence: true
  validates :address, presence: true
  validates :price_per_day, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cars, dependent: :destroy
         has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @car = Car.find(params[:car_id])
    @booking = @car.bookings.new(booking_params)
    @booking.car = @car
    @booking.user = current_user

    if @booking.save
      redirect_to car_path(@car), notice: 'Booking successfully created.'
    else
      render :'car/show', status: :unprocessable_entity
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :accepted)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @cars = Car.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
  <div class="container">
  <div class="row">
    <div class="col-md-6">
      <!-- Car Cards -->
      <% @cars.each do |car| %>
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= link_to car.brand, car %></h5>
            <!-- Other car details -->
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <!-- Image -->
      <div class="banner" style="background-image: url('/assets/chev.jpg');">
        <!-- Content for the image section -->
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="card mb-3">
    <div class="card-body">
      <h1 class="card-title"><%= @car.brand %></h1>
      <p class="card-text"><strong>Year of Production:</strong> <%= @car.year_of_production %></p>
      <p class="card-text"><strong>Address:</strong> <%= @car.address %></p>
      <p class="card-text"><strong>Price per Day:</strong> <%= @car.price_per_day %></p>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Make a Reservation</h2>
      <%= simple_form_for([@car, @booking]) do |form| %>
        <div class="mb-3">
          <%= form.input :starts_at, as: :string, input_html: { id: "booking_starts_at", data: { controller: "datepicker" } }, label: '<strong>Start Date:</strong>'.html_safe %>
        </div>
        <div class="mb-3">
          <%= form.input :ends_at, as: :string, input_html: { id: "booking_ends_at", data: { controller: "datepicker" } }, label: '<strong>End Date:</strong>'.html_safe %>
        </div>
        <%= form.button :submit, 'Reserve Car', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <%= link_to 'Back to Cars', cars_path(@car), class: 'btn btn-secondary mt-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentCarsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <div class="content">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </div>
  </body>
  <footer>
    <%= render "shared/footer" %>
  </footer>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= asset_path('homepage.jpg') %>);">

  <div class="container">
    <h1>Sharing Rides,<strong> Building Connections,</strong>  <strong>  - Carchare</strong>!</h1>
    <p>Unlock the Power of Shared Rides with Carchare: Connect, Share, and Explore the Road Together!"</p>
    <a class="btn btn-flat" href="#"><%= link_to "Book now", cars_path, class:"link-homepage" %></a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar- navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag('logo.jpg', alt: 'Image Description') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <div class="navbar-link">
          <%= link_to "Book now", cars_path %>
          <a href="<%= edit_user_registration_path %>">Account</a>
          <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>

      <% else %>
        <%= link_to "Sign In", new_user_session_path, class:"navbar-item, btn btn-warning" %>
        <%= link_to "Sign up", new_user_registration_path, class:"navbar-item, btn btn-warning"%>
      <% end %>
       </div>

      </ul>
    </div>
  </div>
</div>